threads: 8
fastqDir: "Tvt_p4_fastq/"
samples: "config/samples_TvTp4.tsv"
reference: "resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
refdict: "resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.dict"
known: "resources/00-common_all.vcf.gz"
pon: "resources/somatic-hg38_1000g_pon.hg38.vcf.gz"
outdir: "results"
regions:  "config/CD7_exon_amplicons.bed"
primers: "config/cd7_exon_cutadapt_adapters.tsv"