threads: 8
samples: "config/samples_TvT10.tsv"
reference: "resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
refdict: "resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.dict"
known: "resources/00-common_all.vcf.gz"
outdir: "results"
regions:  "config/CD7_exon_amplicons.bed"
primers: "config/cd7_exon_cutadapt_adapters.tsv"