threads: 2
samples: "config/samples.tsv"
reference: "resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
refdict: "resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.dict"
known: "resources/00-common_all.vcf.gz"
outdir: "results"
regions:  "resources/cd7_locus_hg38.bed"