threads: 8
fastqDir: "data/"
samples: "config/example_samples.tsv"
reference: "resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
refdict: "resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.dict"
known: "resources/00-common_all.vcf.gz"
pon: "resources/somatic-hg38_1000g_pon.hg38.vcf.gz"
germline: "resources/somatic-hg38_af-only-gnomad.hg38.vcf.gz"
outdir: "results"
regions:  "config/example_amplicons.bed"
primers: "config/example_cutadapt_adapters.tsv"
